// Copyright (C) 2016  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Intel and sold by Intel or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 16.1 (Build Build 196 10/24/2016)
// Created on Tue May 15 22:07:38 2018

jk_ff_async jk_ff_async_inst
(
	.q(q_sig) ,	// output  q_sig
	.j(j_sig) ,	// input  j_sig
	.k(k_sig) ,	// input  k_sig
	.pre_n(pre_n_sig) ,	// input  pre_n_sig
	.clr_n(clr_n_sig) ,	// input  clr_n_sig
	.clk_n(clk_n_sig) 	// input  clk_n_sig
);

